name: app

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./espq

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -V
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Run linters
        uses: quentinguidee/pep8-action@v1

  snyk:
    runs-on: ubuntu-latest
    container: snyk/snyk:python-3.9
    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --sarif-file-output=../snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif